### ISSUE TITLE
Release Links Broken

### ISSUE THREAD

**Issue by infinitLoop** [worproject/RPi-Windows-Drivers#1]
The downloads appear to be broken - they result in "The request signature we calculated does not match the signature you provided. Check your key and signing method."  Also, trying to download latest from the net in the install is resulting in a 403 Forbidden error.

**Comment by worproject** [comment]
They're not broken. I'm able to download all the archives in the latest release.

**Comment by infinitLoop** [comment]
It looks like they are working again for me too.  Maybe just a temporary issue I guess.
