### ISSUE TITLE
Audio Jack sounds very funny

### ISSUE THREAD

**Issue by CE1CECL** [worproject/RPi-Windows-Drivers#12]
not sure if anyone else has this issue but mine sounds like higher pitched.

**Comment by mariobalanica** [comment]
What Raspberry Pi model?
Clock speeds?

**Comment by CE1CECL** [comment]
Hi there
It seems like it only does it when booting from HDD 2Tb, I’m using pi4 and it doesn’t do it when using sd card, not sure if this is an issue with the pi itself or not.
It has not been overclocked either

**Comment by CE1CECL** [comment]
Also what’s weird about it is that when I boot from the 2TB disk, it shows a black border around the screen, where as sd card it doesn’t so it may be a pi issue

**Comment by mariobalanica** [comment]
Fixed in the latest release.
