### ISSUE TITLE
Audio driver problem

### ISSUE THREAD

**Issue by Theo-BEST** [worproject/RPi-Windows-Drivers#13]
I installed the audio driver (and pwm driver) and the sound produced by the audio output is slowly (and consequently deformed) than the original sound, I don't know why it is like this but I calculed that the sound is nearly at 92% of the original speed.

**Comment by mariobalanica** [comment]
What UEFI version?

**Comment by Theo-BEST** [comment]
EDK2 lampone 8f088a12 on 12/13/2020, 12/12/2020

**Comment by mariobalanica** [comment]
Looks like it's a custom build. You need the latest firmware package for the audio driver to work correctly.
https://github.com/pftf/RPi4/releases
