### ISSUE TITLE
Dual monitor support with basic driver

### ISSUE THREAD

**Issue by ghost** [worproject/RPi-Windows-Drivers#17]
Hi, there is any way to enable dual screen support also if actualy there is no working driver video?

For helping in build the driver video there are some resource (or documentation) about the work to do and the actual stete of the driver?

**Comment by Theo-BEST** [comment]
The team of the WoR project as already create a dual display driver but for the moment, it is in test by the team but if you want try it the team can give you the driver at your own risk on the discord server by private message

**Comment by ghost** [comment]
Thanks for this update. How i can ask for the experimental driver to discord?

**Comment by mariobalanica** [comment]
You can find a link to the Discord server here: https://worproject.ml/community

**Comment by ghost** [comment]
If anyone is interested: https://github.com/themindvirus/pi4bdd
