### ISSUE TITLE
Getting the Optiga™ SLB 9670 TPM 2.0 chip to work

### ISSUE THREAD

**Issue by Daszbin** [worproject/RPi-Windows-Drivers#22]
I have the Optiga™ SLB 9670 TPM 2.0 chip it works well in raspbian however in Windows 10 or Windows 11 it doesn’t show up. I know there is to be supposed driver that Windows IOT can use to make it work. Is it possible to get it to work with WOR.

**Comment by mariobalanica** [comment]
Looks like the ARM32 UEFI has support for this: https://github.com/ms-iot/RPi-UEFI/commit/0e2bf04ff3a48e7bf25092f1e1fd7dca16c6f109

I suggest opening the issue here: https://github.com/pftf/RPi4/issues
