### ISSUE TITLE
GPU driver not working

### ISSUE THREAD

**Issue by JeromTWinL** [worproject/RPi-Windows-Drivers#28]
Gpu not working makes windows 10 pi 3 too slow

**Comment by ToBiDi0410** [comment]
I think there never were any "working" GPU Drivers. There was a Beta Driver that allowed you to have two monitors, but no Hardware Acceleration.

**Comment by JeromTWinL** [comment]
Hmm, it can be skipped if no over cpu usage, but there is high cpu and ram usage.

**Comment by JeromTWinL** [comment]
Ok , I'm closing this issue.
