### ISSUE TITLE
Which driver is for which device ID in windows device manager?

### ISSUE THREAD

**Issue by jayjupdhig** [worproject/RPi-Windows-Drivers#30]
...instead of trying every combination!?

-> https://github.com/worproject/RPi-Windows-Drivers/releases

![image](https://user-images.githubusercontent.com/42765391/142879376-7cc2d3e8-d575-4626-9843-9083fbeb0407.png)

**Comment by binarymaster** [comment]
`BCM2850` is Video Core 4 GPU

For more see: https://github.com/tianocore/edk2-platforms/blob/194269223294bb30513837d3582a6a635b672661/Platform/RaspberryPi/AcpiTables/GpuDevs.asl#L39

**Comment by kosuodhmwa** [comment]
Thank you very much. But i don't just me that device. So you see, there are 5 unknown devices on my RPi 4 with Windows 11 Pro.

There is no list which device need what driver?

**Comment by binarymaster** [comment]
I don't really know whether Windows ACPI supports displaying something as a device friendly name, when the driver is not installed for it yet.

**Comment by kosuodhmwa** [comment]
So try-and-error - trying every combination? :-)

**Comment by kosuodhmwa** [comment]
???

**Comment by mariobalanica** [comment]
There are no drivers for those "Unknown devices".

**Comment by kosuodhmwa** [comment]
ok thx

**Comment by kosuodhmwa** [comment]
But for what are the drivers on https://github.com/worproject/RPi-Windows-Drivers/releases ?

**Comment by mariobalanica** [comment]
https://github.com/worproject/RPi-Windows-Drivers#status

**Comment by kosuodhmwa** [comment]
ok thx
