### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by MinGW32-2006** [worproject/RPi-Windows-Drivers#47]
It's 2023 now. Is the project still under development or it's dead? The latest repository update is almost one year ago.

**Comment by Mabbs** [comment]
rpi is dead, so the project is also dead

**Comment by commandcontrolQ** [comment]
> rpi is dead, so the project is also dead

What makes you think that the Raspberry Pi is dead? Just curious.

**Comment by Mabbs** [comment]
> > rpi is dead, so the project is also dead
> 
> What makes you think that the Raspberry Pi is dead? Just curious.

Because it hasn't been updated for a long time

**Comment by MinGW32-2006** [comment]
So there is someone writing the GPU driver FROM SCRATCH? I'll wait for it. :)

**Comment by binarymaster** [comment]
> So there is someone writing the GPU driver FROM SCRATCH?

GPU driver question is being tracked in #3.

**Comment by MinGW32-2006** [comment]
> > So there is someone writing the GPU driver FROM SCRATCH?
> 
> GPU driver question is being tracked in #3.

I see. Thanks for you reply. :)

**Comment by RetroSoftwareRepository** [comment]
> rpi is dead, so the project is also dead

It's not dead.... The Pi 5 is a thing now.
