### ISSUE TITLE
Rpi 3B+ stuck on 0.6ghz

### ISSUE THREAD

**Issue by sprtkd** [worproject/RPi-Windows-Drivers#8]
Rpi 3B+ stuck with 0.6ghz even with setting 1400 in config.txt.
Any known fix would be really helpful.
Using 20H2 arm64.

**Comment by worproject** [comment]
Do you see any lightning bolt on the screen / or does the red LED flash?

**Comment by sprtkd** [comment]
Yes, but after changing the power supply, it got stuck at 1.2ghz with 100% cpu usage.

**Comment by worproject** [comment]
This seems like a power issue.
