### ISSUE TITLE
 Driver signature

### ISSUE THREAD

**Issue by bzy-080408** [worproject/RPi-Windows-Drivers#9]
(rpi4) when I tried to turn on the Hyper-V function, I found that I had to turn off the test mode, but after turning it off, I was prompted that the driver signature was invalid（ rpiq.sys )

**Comment by mariobalanica** [comment]
From the readme:
> most of the drivers require the Test Signing mode to be enabled.

Also, Hyper-V doesn't work at the moment as the UEFI doesn't declare support for it. You can open this issue here: https://github.com/pftf/RPi4
